### ISSUE TITLE
Support for ed25519 on smartcards

### ISSUE THREAD

**Issue by 0x5c** [cotechde/termbot#37] opened 2020-11-09 23:22 UTC
## Describe the solution you'd like

The app successfully imports ed25519 keys from devices meeting the OpenPGP smartcard standard, including the YubiKeys. 

## Describe alternatives you've considered

OpenKeychain does include support for ed25519 keys on OpenPGP smartcards, so bringing support for OpenKeychain would also fix this problem.

**Comment by dschuermann** [comment] 2020-12-18 18:31
duplicate of https://github.com/cotechde/termbot/issues/11

**Closed as completed by dschuermann** 2020-12-18 18:31 UTC
